name: Python Unit Tests

on:
  push:
    branches:
      - main  # Change this to your main branch
  pull_request:
    branches:
      - main  # Change this to your main branch
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11  # Change this to your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Change this to your requirements file if applicable

    - name: Run mypy
      run: |
        python -m mypy .

    - name: Run tests
      run: |
        python -m unittest discover -s tests  # Change this to your test directory


